# USB + Bluetooth
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Bluetooth name
CONFIG_BT_DEVICE_NAME="Macropad"
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
